
[general]

	#CopperGolem
	[general.coppergolem]

		#Max. search range for buttons
		[general.coppergolem.maxwaitingtime]
			#Range: > 0
			maxwaittime = 200
			#Range: > 0
			searchbutton = 20

		#Random Button Press
		[general.coppergolem.randompress]
			randompress = true

		#Base Health
		[general.coppergolem.health]
			#Range: > 0
			health = 50

		#Base Damage
		[general.coppergolem.damage]
			#Range: > 0
			damage = 8

		#Healing from cooper ingot
		[general.coppergolem.heal]
			#Range: > 0
			heal = 25

