name = "Crafters Modpack"
author = "Bksp"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "740f25c78032d1e617d110d1e3d4c7c9d05f4d6a267c105a85e89f266aff5120"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
