name = "Crafters Modpack"
author = "Bksp"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91977f6b8d25dc9fe3d28e872b1a89550f5c1fad1093c26c828b496106453a9c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
