name = "Crafters Modpack"
author = "Bksp"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53502d696e76095451e3ca6987405d08f0c9f89e61cb3bb68f9675f5b331dd1a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
