
[General]
	#Allowed Values: DISPLAY_ALL, DISPLAY_MY, DISPLAY_OTHERS, HIDE
	"Pet Mode" = "HIDE"

[Tooltips]
	#Display food properties in tooltips
	"Food Icons" = false
	#Display equipment attributes in tooltips
	"Equipment Icons" = false

